### ISSUE TITLE
[Improvement] Add Unicode Font for GUI

### ISSUE THREAD

**Issue by shikulja** [Vociferous121/Ogasai#3]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/3386359/203577872-bd03f05b-8237-469c-89e3-93600fe40a7d.png">

To check the font, you can use my text, replacing it manually, for core.lua
	["Grind options"] = "Настройки гринда",
	["Follower options"] = "Настройки следования",
	["Fishing options"] = "Настройки рыбалки",
	["Combat options"] = "Настройки боя",

**Comment by Vociferous121** [comment]
Cannot change. Source code for bot is not accessible.
