### ISSUE TITLE
[script_followEX] 34: attempt to index a number value

### ISSUE THREAD

**Issue by shikulja** [Vociferous121/Ogasai#5]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/3386359/204138830-059770da-0c92-46ad-a926-6bcf1ab25e33.png">

**Comment by Vociferous121** [comment]
This is due to not being in a party when activating Follower script. Will not interfere with script.

**Comment by shikulja** [comment]
I know. but you need to add a check with a message. So that people don't get confused

**Comment by Vociferous121** [comment]
The check is in now place. Should not affect followers.

The follower script is heavily bugged. The bot was NOT made to do this and it's a script taking advantage of in-game API.

if (getPartyMembers() ~= nil) then

**Comment by Vociferous121** [comment]
There is currently a bug with looting with new updated scripts. Everything works but it is returning an error I have not resolved yet.

In situations like these it is best to have an addon called 'Improved Error Frames'. This will move the errors to a bubble under the mini-map.

**Comment by Vociferous121** [comment]
Issue has been fixed, though I am not sure if individual follower scripts have any errors relating to this.
